### PR TITLE
Fix Issue #24

### PR DESCRIPTION
**Pull request by tonyhhyip**

### CODE REVIEW

**Comment by yookoala** [comment]
As spoken,
1. We do not do advertisement based on cookies tracking in this site.
2. We use Google Analytics, which tracks cookie and user agent data, for traffic analysis and conversion tracking.
3. We have set the data retention period of our Google Analytics account to 14 months.
3. Should anyone want to remove their personal data in our possession, please contact conference@opensource.hk .

**Comment by yookoala** [comment]
The bottom notice is too long. Need to balance between clarity and concision.

I think a sentence like this might be better for reading (also occupies less screen area): 
unnamed

Also using white-on-black color scheme seems to look better.

**Comment by yookoala** [comment]
Maybe change to something like this?

"We use cookies on this website for traffic analysis. By using this site, you agree that we may store and access cookies on your device."

[Find out more] [Got it]

**Comment by tonyhhyip** [comment]
But I do see some article say this is not enough

**Comment by yookoala** [comment]
Can you provide a link of the article you read?

**Comment by tonyhhyip** [comment]
https://www.itgovernance.eu/blog/en/how-the-gdpr-affects-cookie-policies
https://www.cookiebot.com/en/gdpr-cookies/

**Comment by yookoala** [comment]
If we are to fully implement GDPR compliant cookie law notice [as described](https://www.itgovernance.eu/blog/en/how-the-gdpr-affects-cookie-policies), we should not track cookie until the user give his / her consent. That means we need to change our GA script to NOT running until user Opt-in.

Do you have time to do that?

**Comment by yookoala** [comment]
Text change to this, probably:

"We use cookies on this website for marketing insights to improve HKOSCon. Please allow us in supporting the cause. We promise we'd be good."

[Find out more] [Accept]

**Comment by tonyhhyip** [comment]
@yookoala The text is already updated

**Comment by yookoala** [comment]
Still pending the actual Opt-in logic. To be truthful to the opt-in claim, we'd need to check cookie for "Opt In" before we run the Google Tag Manager / Google Analytics logic.

**Review by yookoala — APPROVED** [review]

**Pull request merged**
